name: FeliCraft-Punishment
version: '${project.version}'
main: fr.ju.feliCraftPunisment.FeliCraftPunisment
api-version: '1.20'
depend: [AdvancedBan]
author: FeliCraft Team
description: Plugin de gestion des sanctions avec GUI pour AdvancedBan

commands:
  ss:
    description: Ouvre le menu de sanctions pour un joueur
    usage: /<command> <joueur>
    aliases: [screenshare, sanction]

permissions:
  felix.use:
    description: Permet d'utiliser la commande /ss et d'accéder au menu de sanctions
    default: op
  felix.mute:
    description: Permet d'accéder à la catégorie des mutes dans le menu de sanctions
    default: op
  felix.ban:
    description: Permet d'accéder à la catégorie des bans dans le menu de sanctions
    default: op